package com.cping.jo.enums

enum class MenuElement {
    //Visual
    MENU_VISUAL_ESP_SKELETON,
    MENU_VISUAL_ESP_NAME,
    MENU_VISUAL_ESP_HEALTH,
    MENU_VISUAL_ESP_BOX,
    MENU_VISUAL_ESP_DISTANCE,

    // Combat
    MENU_COMBAT_IS_AIMBOT,
    MENU_COMBAT_AIMBOT_FOV,
    MENU_COMBAT_AIMBOT_SENSITIVITY,

    // Section
    MENU_SECTION_VISUAL,
    MENU_SECTION_COMBAT,
    MENU_SECTION_SETTING,
}