package com.cping.jo.enums

enum class MenuElement {
    // Visual
    MENU_VISUAL_ESP_BOX,
    MENU_VISUAL_ESP_HEALTH,
    MENU_VISUAL_ESP_NAME,
    MENU_VISUAL_ESP_MARKS,

    // Combat
    MENU_COMBAT_IS_AIM,
    MENU_COMBAT_AIM_FOV,
    MENU_COMBAT_AIM_TOUCH_X,
    MENU_COMBAT_AIM_TOUCH_Y,
    MENU_COMBAT_AIM_TOUCH_RADIUS,
    MENU_COMBAT_AIM_ZONE_FIRE_X,
    MENU_COMBAT_AIM_ZONE_FIRE_Y,
    MENU_COMBAT_AIM_ZONE_FIRE_RADIUS,
    MENU_COMBAT_AIM_SENSITIVITY_FACTOR,
    MENU_COMBAT_AIM_LATENCY_DRAG,
    MENU_COMBAT_AIM_SWIPE_DURATION,

    UNKNOWN
}